{
    'name': 'Odoo AutoServices',
    'version': '12.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'AutService',
    'sequence': '10',
    'license': 'MB001',
    'author': 'Marcos Bolivar',
    'maintainer': 'Marcos Bolivar',
    'website': 'www.google.com',
    'depends': ['sale', 'mail', 'report_xlsx', 'web_timeline'],
    'demo': [],
    'data': [
#        'security/security.xml',
#        'security/ir.model.access.csv',
#        'data/sequence.xml',
#        'data/data.xml',
#        'data/cron.xml',
#        'wizards/create_appointment.xml',
#        'views/patient.xml',
#        'views/appointment.xml',
#        'views/doctor.xml',
#        'views/lab.xml',
#        'views/sale_order.xml',
#        'views/template.xml',
#        'views/settings.xml',
#        'reports/patient_card.xml',
#        'reports/report.xml',
#        'reports/sale_report_inherit.xml',
#        'reports/appointment.xml',
#        'data/mail_template.xml',
#        'views/website_form.xml',
    ],
#  'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
# Video Explanation: https://www.youtube.com/watch?v=BDepk0LhVuI&list=PLqRRLx0cl0hoJhjFWkFYowveq2Zn55dhM&index=1
